#!/bin/sh

# mouse sensitivity
sudo mkdir -p /etc/X11/xorg.conf.d
sudo cp 50-mouse-acceleration.conf /etc/X11/xorg.conf.d

# skip username when loging in with tty
sudo mkdir -p /etc/systemd/system/getty@tty1.service.d
sudo cp skip-username.conf /etc/systemd/system/getty@tty1.service.d

# disable beep sound in tty
sudo mkdir -p /etc/modprobe.d
sudo cp nobeep.conf /etc/modprobe.d

# darkman config
sudo cp -r ~/.local/bin/darkman/* /usr/local/share/

# turn off bluetooth on start
