#!/bin/sh

# mouse sensitivity
sudo mkdir -p /etc/X11/xorg.conf.d
sudo cp 50-mouse-acceleration.conf /etc/X11/xorg.conf.d

# skip username when loging in with tty
sudo mkdir -p /etc/systemd/system/getty@tty1.service.d
sudo cp skip-username.conf /etc/systemd/system/getty@tty1.service.d

# disable beep sound in tty
sudo mkdir -p /etc/modprobe.d
sudo cp nobeep.conf /etc/modprobe.d

# turn off bluetooth on start
sudo sed -i "s/#AutoEnable=true/AutoEnable=false/" /etc/bluetooth/main.conf

# Some pacman settings
sudo sed -i "s/#Color/Color/" /etc/pacman.conf
sudo sed -i "s/#VerbosePkgLists/VerbosePkgLists/" /etc/pacman.conf

# unbind ctrl + alt + l in xfce settings
xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Primary><Alt>l" -r
