#!/bin/sh

# Controller
uuid=$(bluetoothctl list | awk '/default/ { print $2 }')
status=$(bluetoothctl show $uuid | awk '/PowerState/ { print $2 }')

if [[ $status = off ]]; then
	echo 󰂲
else
	if [[ $(bluetoothctl devices Connected | head -n 1 | wc -w) = 0 ]]; then
		echo 󰂯
	else
		echo 󰂱
	fi
fi
