#!/bin/sh

if [[ $(cmus-remote -Q | wc -l) = 0 ]]; then
	echo 󰝛
else
	status=$(cmus-remote -Q | grep status | cut -d ' ' -f 2-)
	if [[ $status = stopped ]]; then
		echo 󰝚
	else
		secToMin() {
			date -ud @$1 +%M:%S
		}

		duration=$(cmus-remote -Q | grep duration | cut -d ' ' -f 2-)
		position=$(cmus-remote -Q | grep position | cut -d ' ' -f 2-)

		duration=$(secToMin $duration)
		position=$(secToMin $position)

		name=$(cmus-remote -Q | grep file | cut -d / -f 6-)
		name=${name%.*}

		echo "󰝚 $name $position / $duration"
	fi
fi
