[window]
padding = { x = 4, y = 4 }

[font]
size = 9

# Gnome (Gnome Terminal Default)

# Default colors
[colors.primary]
background = '#101010'
foreground = '#b9b9b9'

# Normal colors
[colors.normal]
black      = '#101010'
red        = '#c01c28'
green      = '#26a269'
yellow     = '#a2734c'
blue       = '#12488b'
magenta    = '#a347ba'
cyan       = '#2aa1b3'
white      = '#b9b9b9'

# Bright colors
[colors.bright]
black      = '#525252'
red        = '#f66151'
green      = '#33d17a'
yellow     = '#e9ad0c'
blue       = '#2a7bde'
magenta    = '#c061cb'
cyan       = '#33c7de'
white      = '#f7f7f7'
